[package]
name = "markdown-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
js-sys = "0.3.40"
wasm-bindgen = "0.2.63"
pulldown-cmark = {version = "0.8", default-features = false}

[dependencies.web-sys]
features = [
    'Window',
]
version = "0.3.4"

[lib]
crate-type = ["cdylib", "rlib"]
